feat: TOOLS-2245 add ability to limit number of records returned
aerospike/aql pull request #20
Opened 2023-03-15 19:53 UTC by jdogmcsteezy

In addition to the new feature, I also added a new e2e testing infrastructure.

2023-03-16 00:33 UTC, jdogmcsteezy commented
@dwelch-spike, I am going to add another ticket to this PR

2023-04-05 21:35 UTC, dwelch-spike requested changes
Some things from our review and some suggestions.

Mostly make sure that the info response/request and as_hashmap entries are being cleaned up correctly. Some valgrind runs with the new double where clause functionality should help.

Non blocking suggestions
- Adding an error struct or enum so that functions that return bool errors could return more information or error messages could be helpful. This could improve error messages and reduce repeated error checking.
- Maybe in the future, implementing a where clause vector rather than an explicit 2nd where clause could help if we ever need to support > 2.
- I think avoiding nested callbacks where possible will improve code clarity.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_parser.c
> +	free(peek);
"AND"

Suggestion: A comment about what error case this handles. Maybe an example input that causes it.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_parser.c
> +	if (tknzr->tok && !strcasecmp(tknzr->tok, "LIMIT") && !parse_limit(tknzr, &limit))
Suggestion: A comment about what error case this handles. Maybe an example input that causes it.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_parser.c
> +parse_skey(tokenizer *tknzr, asql_where *where, asql_where **where2)
Suggestion: you could do something similar to the c client with as_error where you return an enum error code instead of a bool, or a struct with a code and error message. That way you could encode information about why it failed instead of having to do checks like on line 1369.
`if (tknzr->tok && ((!strcasecmp(tknzr->tok, "and") && s->where.qtype != ASQL_QUERY_TYPE_NONE) || s->where2 != NULL)) {`

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/sql-lexer.l
> +         *token = yycopy;
Suggestion: a comment explaining why this is important.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_query.c
> +	as_vector* responses = as_vector_create(sizeof(as_hashmap*), 128);
I think the info request and responses need to be freed.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_query.c
> +	if (aerospike_info_foreach(g_aerospike, err, NULL, req, cardinality_callback, &total_epb) != AEROSPIKE_OK) {
I think you have to free the responses.

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_query.c
> +	asql_query_type_t query_type = s->where.qtype;
Use chosen_where.qtype

2023-04-05 21:35 UTC, dwelch-spike commented on src/main/asql_query.c
> +		if (chosen_where->beg.type == AS_INTEGER) { // Integer Range
Use query_type after it is changed to chosen_where.qtype

2023-04-05 21:36 UTC, dwelch-spike commented on src/main/asql.c
> +	destroy_where(s->where2);
because the second where is a pointer :)))

2023-04-06 01:52 UTC, jdogmcsteezy commented on src/include/asql_info_parser.h
> + * Copyright 2015-2022 Aerospike, Inc.
I'd rather do a commit to update them all after

2023-04-06 01:52 UTC, jdogmcsteezy commented on src/main/asql_conf.c
>  						base->password = argv[optind++];
It probably does

2023-04-06 02:03 UTC, jdogmcsteezy commented on src/main/asql_query.c
> +	if (aerospike_info_foreach(g_aerospike, err, NULL, req, cardinality_callback, &total_epb) != AEROSPIKE_OK) {
Only the request in this case

2023-04-06 19:24 UTC, dwelch-spike approved these changes
LGTM

2023-04-06 20:03 UTC, merged