fix: TOOLS-2962 Handle boolean values on JSON bin value
aerospike/aql pull request #33
Opened 2024-09-16 11:14 UTC by a-spiker

Verified:

# Test 1:
```
aql> INSERT INTO test.myset (PK, foo, bar) VALUES ('key1',true,JSON('{"a":false,"b": [1, 2, 3]}'))
OK, 1 record affected.
```

```
aql> select * from test.myset
+--------+------+-----------------------------------+
| PK     | foo  | bar                               |
+--------+------+-----------------------------------+
| "key1" | true | MAP('{"a":false, "b":[1, 2, 3]}') |
+--------+------+-----------------------------------+
1 row in set (0.009 secs)

OK
```

# Test 2:
```
aql> INSERT INTO test.myset (PK, foo, bar) VALUES ('key1',true,JSON('{"a":true,"b": [1, 2, 3]}'))
OK, 1 record affected.
```

```
aql> select * from test.myset
+--------+------+----------------------------------+
| PK     | foo  | bar                              |
+--------+------+----------------------------------+
| "key1" | true | MAP('{"a":true, "b":[1, 2, 3]}') |
+--------+------+----------------------------------+
1 row in set (0.012 secs)

OK
```

2024-09-16 18:00 UTC, jdogmcsteezy requested changes
We should also update the help text output to use a nested boolean value

2024-09-17 05:12 UTC, a-spiker commented
Test 3:
```
aql> INSERT INTO test.demo (PK, foo, bar, baz) VALUES ('key1', CAST('123' AS INT), LIST('[true, false, true]'), BOOL(1))
OK, 1 record affected.

aql> select * from test.demo;
+--------+-----+-----------------------------+------+
| PK     | foo | bar                         | baz  |
+--------+-----+-----------------------------+------+
| "key1" | 123 | LIST('[true, false, true]') | true |
+--------+-----+-----------------------------+------+
1 row in set (0.010 secs)

OK

```

Test 4:
```
aql> INSERT INTO test.myset (PK, foo, bar) VALUES ('key1',true,MAP('{"a":true,"b": [1, 2, true]}'))
OK, 1 record affected.

aql> select * from test.myset;
+--------+------+-------------------------------------+
| PK     | foo  | bar                                 |
+--------+------+-------------------------------------+
| "key1" | true | MAP('{"a":true, "b":[1, 2, true]}') |
+--------+------+-------------------------------------+
1 row in set (0.014 secs)

OK

```

2024-09-17 08:21 UTC, sunilvirus approved these changes
The change looks good. Long back the server was not supporting boolean values and that support was added later. Looks like we did not update our aql to catchup with that and hence the problem.

2024-09-17 15:52 UTC, jdogmcsteezy approved these changes

2024-09-17 16:11 UTC, merged